HW17/homeworkWebApp/homeworkWebApp/Models/ErrorViewModel.cs
namespace homeworkWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HW17/homeworkWebApp/homeworkWebApp/Controllers/FirstController.cs
using Microsoft.AspNetCore.Mvc;

namespace homeworkWebApp.Controllers
{
    public class FirstController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.MyBag = "First page";
            return View();
        }
    }
}

HW17/homeworkWebApp/homeworkWebApp/Controllers/HomeController.cs
using homeworkWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace homeworkWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HW17/homeworkWebApp/homeworkWebApp/Controllers/LastController.cs
using Microsoft.AspNetCore.Mvc;

namespace homeworkWebApp.Controllers
{
    public class LastController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.MyBag = "First page";
            return RedirectToAction("Index1");
        }
        
        [HttpGet]
        public async Task Index1()
        {
            string content = @"<form method='post'>
                <label>What's your mood today?:</label><br />
                <input name='mood' /><br />
                <label>What part of the day is right now?:</label><br />
                <input  name='day' /><br />
                <input type='submit' value='Send' />
            </form>";
            Response.ContentType = "text/html;text/html";
            await Response.WriteAsync(content);
        }
        [HttpPost]
        public string Index1(string mood, string day) => $"It is a {mood} {day}, isn't it?";
    }
}

HW17/homeworkWebApp/homeworkWebApp/Controllers/SecondController.cs
using Microsoft.AspNetCore.Mvc;

namespace homeworkWebApp.Controllers
{
    public class SecondController : Controller
    {
        public IActionResult Index()
        {
            //ViewBag.MyBag = "Second page";
            //return View();
            return Redirect("http://localhost:5193/First");
        }
    }
}

HW17/homeworkWebApp/homeworkWebApp/Views/First/Index.cshtml
@{
    
    ViewData["Title"] = "Hello";
}

<h1> @ViewData["Title"]</h1>
<p> This is my first page</p>
<p> @ViewBag.MyBag</p>

HW17/homeworkWebApp/homeworkWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HW17/homeworkWebApp/homeworkWebApp/Views/Last/Index.cshtml
@{
    ViewData["Title"] = "See you later";
}

<h1> @ViewData["Title"]</h1>
<p> This is my last page</p>
<p> @ViewBag.MyBag</p>

HW17/homeworkWebApp/homeworkWebApp/Views/Second/Index.cshtml
@{
    ViewData["Title"] = "Bye";
}

<h1> @ViewData["Title"]</h1>
<p> This is my second page</p>
<p> @ViewBag.MyBag</p>

HW17/homeworkWebApp/homeworkWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - homeworkWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/homeworkWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">homeworkWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
      <a class="nav-link text-dark" asp-area="" asp-controller="First" asp-action="Index">First page</a>
</li>
<li class="nav-item">
      <a class="nav-link text-dark" asp-area="" asp-controller="Second" asp-action="Index">Second page</a>
</li>
<li class="nav-item">
      <a class="nav-link text-dark" asp-area="" asp-controller="Last" asp-action="Index">Last Page</a>
</li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - homeworkWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>